################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/src/Clock_Ip.c \
../src/src/Clock_Ip_Cfg.c \
../src/src/Clock_Ip_Data.c \
../src/src/Clock_Ip_Divider.c \
../src/src/Clock_Ip_DividerTrigger.c \
../src/src/Clock_Ip_ExtOsc.c \
../src/src/Clock_Ip_FracDiv.c \
../src/src/Clock_Ip_Frequency.c \
../src/src/Clock_Ip_Gate.c \
../src/src/Clock_Ip_IntOsc.c \
../src/src/Clock_Ip_Irq.c \
../src/src/Clock_Ip_Monitor.c \
../src/src/Clock_Ip_PBcfg.c \
../src/src/Clock_Ip_Pll.c \
../src/src/Clock_Ip_ProgFreqSwitch.c \
../src/src/Clock_Ip_Selector.c \
../src/src/Clock_Ip_Specific.c \
../src/src/Det.c \
../src/src/Det_stub.c \
../src/src/Dio.c \
../src/src/Dio_Cfg.c \
../src/src/Dio_Ipw.c \
../src/src/Gpio_Dio_Ip.c \
../src/src/IntCtrl_Ip.c \
../src/src/IntCtrl_Ip_Cfg.c \
../src/src/Mcu.c \
../src/src/Mcu_Cfg.c \
../src/src/Mcu_Dem_Wrapper.c \
../src/src/Mcu_IPW.c \
../src/src/Mcu_IPW_Irq.c \
../src/src/Mcu_PBcfg.c \
../src/src/OsIf_Cfg.c \
../src/src/OsIf_Timer.c \
../src/src/OsIf_Timer_System.c \
../src/src/Platform.c \
../src/src/Platform_Cfg.c \
../src/src/Platform_Ipw.c \
../src/src/Platform_Ipw_Cfg.c \
../src/src/Port.c \
../src/src/Port_Cfg.c \
../src/src/Port_Ci_Port_Ip.c \
../src/src/Port_Ci_Port_Ip_PBcfg.c \
../src/src/Port_Ipw.c \
../src/src/Port_PBcfg.c \
../src/src/Power_Ip.c \
../src/src/Power_Ip_CMU.c \
../src/src/Power_Ip_Cfg.c \
../src/src/Power_Ip_CortexM4.c \
../src/src/Power_Ip_PBcfg.c \
../src/src/Power_Ip_PCC.c \
../src/src/Power_Ip_PMC.c \
../src/src/Power_Ip_PMC_Irq.c \
../src/src/Power_Ip_Private.c \
../src/src/Power_Ip_RCM.c \
../src/src/Power_Ip_RCM_Irq.c \
../src/src/Power_Ip_SCG.c \
../src/src/Power_Ip_SIM.c \
../src/src/Power_Ip_SMC.c \
../src/src/Ram_Ip.c \
../src/src/Ram_Ip_Cfg.c \
../src/src/Ram_Ip_PBcfg.c \
../src/src/SchM_Adc.c \
../src/src/SchM_Can.c \
../src/src/SchM_Crc.c \
../src/src/SchM_Crypto.c \
../src/src/SchM_Dio.c \
../src/src/SchM_Eep.c \
../src/src/SchM_Eth.c \
../src/src/SchM_Fee.c \
../src/src/SchM_Fls.c \
../src/src/SchM_Gpt.c \
../src/src/SchM_I2c.c \
../src/src/SchM_I2s.c \
../src/src/SchM_Icu.c \
../src/src/SchM_Iseled.c \
../src/src/SchM_Lin.c \
../src/src/SchM_Mcl.c \
../src/src/SchM_Mcu.c \
../src/src/SchM_Ocu.c \
../src/src/SchM_Port.c \
../src/src/SchM_Pwm.c \
../src/src/SchM_Qdec.c \
../src/src/SchM_Rm.c \
../src/src/SchM_Sbc_fs26.c \
../src/src/SchM_Sent.c \
../src/src/SchM_Spi.c \
../src/src/SchM_Uart.c \
../src/src/SchM_Wdg.c \
../src/src/SchM_Wdg_43_fs26.c \
../src/src/System_Ip.c 

OBJS += \
./src/src/Clock_Ip.o \
./src/src/Clock_Ip_Cfg.o \
./src/src/Clock_Ip_Data.o \
./src/src/Clock_Ip_Divider.o \
./src/src/Clock_Ip_DividerTrigger.o \
./src/src/Clock_Ip_ExtOsc.o \
./src/src/Clock_Ip_FracDiv.o \
./src/src/Clock_Ip_Frequency.o \
./src/src/Clock_Ip_Gate.o \
./src/src/Clock_Ip_IntOsc.o \
./src/src/Clock_Ip_Irq.o \
./src/src/Clock_Ip_Monitor.o \
./src/src/Clock_Ip_PBcfg.o \
./src/src/Clock_Ip_Pll.o \
./src/src/Clock_Ip_ProgFreqSwitch.o \
./src/src/Clock_Ip_Selector.o \
./src/src/Clock_Ip_Specific.o \
./src/src/Det.o \
./src/src/Det_stub.o \
./src/src/Dio.o \
./src/src/Dio_Cfg.o \
./src/src/Dio_Ipw.o \
./src/src/Gpio_Dio_Ip.o \
./src/src/IntCtrl_Ip.o \
./src/src/IntCtrl_Ip_Cfg.o \
./src/src/Mcu.o \
./src/src/Mcu_Cfg.o \
./src/src/Mcu_Dem_Wrapper.o \
./src/src/Mcu_IPW.o \
./src/src/Mcu_IPW_Irq.o \
./src/src/Mcu_PBcfg.o \
./src/src/OsIf_Cfg.o \
./src/src/OsIf_Timer.o \
./src/src/OsIf_Timer_System.o \
./src/src/Platform.o \
./src/src/Platform_Cfg.o \
./src/src/Platform_Ipw.o \
./src/src/Platform_Ipw_Cfg.o \
./src/src/Port.o \
./src/src/Port_Cfg.o \
./src/src/Port_Ci_Port_Ip.o \
./src/src/Port_Ci_Port_Ip_PBcfg.o \
./src/src/Port_Ipw.o \
./src/src/Port_PBcfg.o \
./src/src/Power_Ip.o \
./src/src/Power_Ip_CMU.o \
./src/src/Power_Ip_Cfg.o \
./src/src/Power_Ip_CortexM4.o \
./src/src/Power_Ip_PBcfg.o \
./src/src/Power_Ip_PCC.o \
./src/src/Power_Ip_PMC.o \
./src/src/Power_Ip_PMC_Irq.o \
./src/src/Power_Ip_Private.o \
./src/src/Power_Ip_RCM.o \
./src/src/Power_Ip_RCM_Irq.o \
./src/src/Power_Ip_SCG.o \
./src/src/Power_Ip_SIM.o \
./src/src/Power_Ip_SMC.o \
./src/src/Ram_Ip.o \
./src/src/Ram_Ip_Cfg.o \
./src/src/Ram_Ip_PBcfg.o \
./src/src/SchM_Adc.o \
./src/src/SchM_Can.o \
./src/src/SchM_Crc.o \
./src/src/SchM_Crypto.o \
./src/src/SchM_Dio.o \
./src/src/SchM_Eep.o \
./src/src/SchM_Eth.o \
./src/src/SchM_Fee.o \
./src/src/SchM_Fls.o \
./src/src/SchM_Gpt.o \
./src/src/SchM_I2c.o \
./src/src/SchM_I2s.o \
./src/src/SchM_Icu.o \
./src/src/SchM_Iseled.o \
./src/src/SchM_Lin.o \
./src/src/SchM_Mcl.o \
./src/src/SchM_Mcu.o \
./src/src/SchM_Ocu.o \
./src/src/SchM_Port.o \
./src/src/SchM_Pwm.o \
./src/src/SchM_Qdec.o \
./src/src/SchM_Rm.o \
./src/src/SchM_Sbc_fs26.o \
./src/src/SchM_Sent.o \
./src/src/SchM_Spi.o \
./src/src/SchM_Uart.o \
./src/src/SchM_Wdg.o \
./src/src/SchM_Wdg_43_fs26.o \
./src/src/System_Ip.o 

C_DEPS += \
./src/src/Clock_Ip.d \
./src/src/Clock_Ip_Cfg.d \
./src/src/Clock_Ip_Data.d \
./src/src/Clock_Ip_Divider.d \
./src/src/Clock_Ip_DividerTrigger.d \
./src/src/Clock_Ip_ExtOsc.d \
./src/src/Clock_Ip_FracDiv.d \
./src/src/Clock_Ip_Frequency.d \
./src/src/Clock_Ip_Gate.d \
./src/src/Clock_Ip_IntOsc.d \
./src/src/Clock_Ip_Irq.d \
./src/src/Clock_Ip_Monitor.d \
./src/src/Clock_Ip_PBcfg.d \
./src/src/Clock_Ip_Pll.d \
./src/src/Clock_Ip_ProgFreqSwitch.d \
./src/src/Clock_Ip_Selector.d \
./src/src/Clock_Ip_Specific.d \
./src/src/Det.d \
./src/src/Det_stub.d \
./src/src/Dio.d \
./src/src/Dio_Cfg.d \
./src/src/Dio_Ipw.d \
./src/src/Gpio_Dio_Ip.d \
./src/src/IntCtrl_Ip.d \
./src/src/IntCtrl_Ip_Cfg.d \
./src/src/Mcu.d \
./src/src/Mcu_Cfg.d \
./src/src/Mcu_Dem_Wrapper.d \
./src/src/Mcu_IPW.d \
./src/src/Mcu_IPW_Irq.d \
./src/src/Mcu_PBcfg.d \
./src/src/OsIf_Cfg.d \
./src/src/OsIf_Timer.d \
./src/src/OsIf_Timer_System.d \
./src/src/Platform.d \
./src/src/Platform_Cfg.d \
./src/src/Platform_Ipw.d \
./src/src/Platform_Ipw_Cfg.d \
./src/src/Port.d \
./src/src/Port_Cfg.d \
./src/src/Port_Ci_Port_Ip.d \
./src/src/Port_Ci_Port_Ip_PBcfg.d \
./src/src/Port_Ipw.d \
./src/src/Port_PBcfg.d \
./src/src/Power_Ip.d \
./src/src/Power_Ip_CMU.d \
./src/src/Power_Ip_Cfg.d \
./src/src/Power_Ip_CortexM4.d \
./src/src/Power_Ip_PBcfg.d \
./src/src/Power_Ip_PCC.d \
./src/src/Power_Ip_PMC.d \
./src/src/Power_Ip_PMC_Irq.d \
./src/src/Power_Ip_Private.d \
./src/src/Power_Ip_RCM.d \
./src/src/Power_Ip_RCM_Irq.d \
./src/src/Power_Ip_SCG.d \
./src/src/Power_Ip_SIM.d \
./src/src/Power_Ip_SMC.d \
./src/src/Ram_Ip.d \
./src/src/Ram_Ip_Cfg.d \
./src/src/Ram_Ip_PBcfg.d \
./src/src/SchM_Adc.d \
./src/src/SchM_Can.d \
./src/src/SchM_Crc.d \
./src/src/SchM_Crypto.d \
./src/src/SchM_Dio.d \
./src/src/SchM_Eep.d \
./src/src/SchM_Eth.d \
./src/src/SchM_Fee.d \
./src/src/SchM_Fls.d \
./src/src/SchM_Gpt.d \
./src/src/SchM_I2c.d \
./src/src/SchM_I2s.d \
./src/src/SchM_Icu.d \
./src/src/SchM_Iseled.d \
./src/src/SchM_Lin.d \
./src/src/SchM_Mcl.d \
./src/src/SchM_Mcu.d \
./src/src/SchM_Ocu.d \
./src/src/SchM_Port.d \
./src/src/SchM_Pwm.d \
./src/src/SchM_Qdec.d \
./src/src/SchM_Rm.d \
./src/src/SchM_Sbc_fs26.d \
./src/src/SchM_Sent.d \
./src/src/SchM_Spi.d \
./src/src/SchM_Uart.d \
./src/src/SchM_Wdg.d \
./src/src/SchM_Wdg_43_fs26.d \
./src/src/System_Ip.d 


# Each subdirectory must supply rules for building sources it contributes
src/src/%.o: ../src/src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Standard S32DS C Compiler'
	arm-none-eabi-gcc "@src/src/Clock_Ip.args" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


